// config.js
// Central app config for Supabase + Blockchain. Keep keys minimal and safe.
// NOTE: Fill CONTRACT_ABI later with your AyurTraceUnified ABI array.
window.config = {
    // Supabase
    SUPABASE_URL: 'https://xqscmazxfayoxcfwtktq.supabase.co',
    SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhxc2NtYXp4ZmF5b3hjZnd0a3RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODYyODIsImV4cCI6MjA3Mzg2MjI4Mn0.w10Ds9xpm5vQ6TLuR4QWZkE8X-IG-H16e-XwiHWA7hs',

    // Blockchain
    GANACHE_URL: 'HTTP://127.0.0.1:7545',
    CONTRACT_ADDRESS: '0x3946fD5403bA12F070F1728e57838Fec9E1f485a',
    CONTRACT_ABI: [
        // Events
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "string", "name": "batchId", "type": "string" }, { "indexed": true, "internalType": "address", "name": "owner", "type": "address" }, { "indexed": false, "internalType": "string", "name": "cropType", "type": "string" }, { "indexed": false, "internalType": "uint256", "name": "quantity", "type": "uint256" }, { "indexed": false, "internalType": "string", "name": "farmLocation", "type": "string" }, { "indexed": false, "internalType": "bytes32", "name": "photoHash", "type": "bytes32" }, { "indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256" }], "name": "BatchCreated", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "string", "name": "batchId", "type": "string" }, { "indexed": true, "internalType": "address", "name": "owner", "type": "address" }, { "indexed": false, "internalType": "string", "name": "cropType", "type": "string" }, { "indexed": false, "internalType": "uint256", "name": "quantity", "type": "uint256" }, { "indexed": false, "internalType": "string", "name": "farmLocation", "type": "string" }, { "indexed": false, "internalType": "bytes32", "name": "photoHash", "type": "bytes32" }, { "indexed": false, "internalType": "string", "name": "farmerName", "type": "string" }, { "indexed": false, "internalType": "string", "name": "farmerUsername", "type": "string" }, { "indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256" }], "name": "BatchCreatedV2", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "string", "name": "batchId", "type": "string" }, { "indexed": true, "internalType": "address", "name": "updater", "type": "address" }, { "indexed": false, "internalType": "uint8", "name": "oldStatus", "type": "uint8" }, { "indexed": false, "internalType": "uint8", "name": "newStatus", "type": "uint8" }, { "indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256" }], "name": "BatchStatusUpdated", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": false, "internalType": "string", "name": "batchId", "type": "string" }, { "indexed": false, "internalType": "string", "name": "inspectorId", "type": "string" }, { "indexed": false, "internalType": "string", "name": "result", "type": "string" }, { "indexed": false, "internalType": "string", "name": "notes", "type": "string" }, { "indexed": false, "internalType": "uint256", "name": "date", "type": "uint256" }], "name": "InspectionAdded", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "string", "name": "farmerBatchId", "type": "string" }, { "indexed": false, "internalType": "string", "name": "collectorId", "type": "string" }, { "indexed": false, "internalType": "string", "name": "farmerId", "type": "string" }, { "indexed": false, "internalType": "uint256", "name": "collectionDate", "type": "uint256" }], "name": "CollectionAdded", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "string", "name": "batchId", "type": "string" }, { "indexed": false, "internalType": "string", "name": "herbType", "type": "string" }, { "indexed": false, "internalType": "uint256", "name": "quantity", "type": "uint256" }, { "indexed": false, "internalType": "string", "name": "storageLocation", "type": "string" }, { "indexed": false, "internalType": "address", "name": "recordedBy", "type": "address" }], "name": "ProductReceived", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "string", "name": "batchId", "type": "string" }, { "indexed": false, "internalType": "uint256", "name": "quantityDispatched", "type": "uint256" }, { "indexed": false, "internalType": "string", "name": "destination", "type": "string" }, { "indexed": false, "internalType": "address", "name": "recordedBy", "type": "address" }], "name": "ProductDispatched", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "string", "name": "productId", "type": "string" }, { "indexed": false, "internalType": "string", "name": "sourceBatchId", "type": "string" }, { "indexed": false, "internalType": "string", "name": "productType", "type": "string" }, { "indexed": false, "internalType": "string", "name": "manufacturerId", "type": "string" }], "name": "ProductCreated", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "account", "type": "address" }, { "indexed": false, "internalType": "string", "name": "name", "type": "string" }, { "indexed": false, "internalType": "string", "name": "username", "type": "string" }, { "indexed": false, "internalType": "uint8", "name": "role", "type": "uint8" }, { "indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256" }], "name": "ProfileSet", "type": "event" },
        // Read functions
        { "inputs": [{ "internalType": "string", "name": "_batchId", "type": "string" }], "name": "getBatchDetails", "outputs": [{ "internalType": "string", "name": "batchId", "type": "string" }, { "internalType": "string", "name": "cropType", "type": "string" }, { "internalType": "uint256", "name": "quantity", "type": "uint256" }, { "internalType": "string", "name": "harvestDate", "type": "string" }, { "internalType": "string", "name": "farmLocation", "type": "string" }, { "internalType": "bytes32", "name": "photoHash", "type": "bytes32" }, { "internalType": "uint8", "name": "status", "type": "uint8" }, { "internalType": "address", "name": "owner", "type": "address" }, { "internalType": "uint256", "name": "timestamp", "type": "uint256" }], "stateMutability": "view", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_batchId", "type": "string" }], "name": "getBatchDetailsV2", "outputs": [{ "internalType": "string", "name": "batchId", "type": "string" }, { "internalType": "string", "name": "cropType", "type": "string" }, { "internalType": "uint256", "name": "quantity", "type": "uint256" }, { "internalType": "string", "name": "harvestDate", "type": "string" }, { "internalType": "string", "name": "farmLocation", "type": "string" }, { "internalType": "bytes32", "name": "photoHash", "type": "bytes32" }, { "internalType": "uint8", "name": "status", "type": "uint8" }, { "internalType": "address", "name": "owner", "type": "address" }, { "internalType": "uint256", "name": "timestamp", "type": "uint256" }, { "internalType": "string", "name": "farmerName", "type": "string" }, { "internalType": "string", "name": "farmerUsername", "type": "string" }], "stateMutability": "view", "type": "function" },
        { "inputs": [{ "internalType": "address", "name": "_farmerAddress", "type": "address" }], "name": "getFarmerBatchIds", "outputs": [{ "internalType": "string[]", "name": "", "type": "string[]" }], "stateMutability": "view", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_username", "type": "string" }], "name": "getFarmerBatchIdsByUsername", "outputs": [{ "internalType": "string[]", "name": "", "type": "string[]" }], "stateMutability": "view", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_name", "type": "string" }], "name": "getFarmerBatchIdsByName", "outputs": [{ "internalType": "string[]", "name": "", "type": "string[]" }], "stateMutability": "view", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_username", "type": "string" }], "name": "getAccountByUsername", "outputs": [{ "internalType": "address", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" },
        { "inputs": [{ "internalType": "address", "name": "_account", "type": "address" }], "name": "getProfile", "outputs": [{ "internalType": "string", "name": "name_", "type": "string" }, { "internalType": "string", "name": "username_", "type": "string" }, { "internalType": "uint8", "name": "role_", "type": "uint8" }, { "internalType": "address", "name": "account_", "type": "address" }, { "internalType": "uint256", "name": "createdAt_", "type": "uint256" }], "stateMutability": "view", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_username", "type": "string" }], "name": "getProfileByUsername", "outputs": [{ "internalType": "string", "name": "name_", "type": "string" }, { "internalType": "string", "name": "username_", "type": "string" }, { "internalType": "uint8", "name": "role_", "type": "uint8" }, { "internalType": "address", "name": "account_", "type": "address" }, { "internalType": "uint256", "name": "createdAt_", "type": "uint256" }], "stateMutability": "view", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_name", "type": "string" }], "name": "getAddressesByName", "outputs": [{ "internalType": "address[]", "name": "", "type": "address[]" }], "stateMutability": "view", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_username", "type": "string" }], "name": "getBatchIdsByFarmerUsername", "outputs": [{ "internalType": "string[]", "name": "", "type": "string[]" }], "stateMutability": "view", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_name", "type": "string" }], "name": "getBatchIdsByFarmerName", "outputs": [{ "internalType": "string[]", "name": "", "type": "string[]" }], "stateMutability": "view", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_batchId", "type": "string" }], "name": "getInspection", "outputs": [{ "internalType": "string", "name": "", "type": "string" }, { "internalType": "string", "name": "", "type": "string" }, { "internalType": "string", "name": "", "type": "string" }, { "internalType": "string", "name": "", "type": "string" }, { "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "", "type": "string" }], "name": "products", "outputs": [{ "internalType": "string", "name": "productId", "type": "string" }, { "internalType": "string", "name": "sourceBatchId", "type": "string" }, { "internalType": "string", "name": "productType", "type": "string" }, { "internalType": "uint256", "name": "quantityProcessed", "type": "uint256" }, { "internalType": "uint256", "name": "wastage", "type": "uint256" }, { "internalType": "uint256", "name": "processingDate", "type": "uint256" }, { "internalType": "uint256", "name": "expiryDate", "type": "uint256" }, { "internalType": "string", "name": "manufacturerId", "type": "string" }], "stateMutability": "view", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "", "type": "string" }], "name": "inventory", "outputs": [{ "internalType": "string", "name": "batchId", "type": "string" }, { "internalType": "string", "name": "herbType", "type": "string" }, { "internalType": "uint256", "name": "quantity", "type": "uint256" }, { "internalType": "string", "name": "storageLocation", "type": "string" }, { "internalType": "string", "name": "status", "type": "string" }, { "internalType": "bool", "name": "isInitialized", "type": "bool" }], "stateMutability": "view", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_farmerBatchId", "type": "string" }], "name": "getCollection", "outputs": [{ "internalType": "string", "name": "", "type": "string" }, { "internalType": "string", "name": "", "type": "string" }, { "internalType": "string", "name": "", "type": "string" }, { "internalType": "uint256", "name": "", "type": "uint256" }, { "internalType": "string", "name": "", "type": "string" }, { "internalType": "uint256", "name": "", "type": "uint256" }, { "internalType": "string", "name": "", "type": "string" }], "stateMutability": "view", "type": "function" },
        // Write functions
        { "inputs": [{ "internalType": "string", "name": "_batchId", "type": "string" }, { "internalType": "string", "name": "_cropType", "type": "string" }, { "internalType": "uint256", "name": "_quantity", "type": "uint256" }, { "internalType": "string", "name": "_harvestDate", "type": "string" }, { "internalType": "string", "name": "_farmLocation", "type": "string" }, { "internalType": "bytes32", "name": "_photoHash", "type": "bytes32" }], "name": "createBatch", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_batchId", "type": "string" }, { "internalType": "string", "name": "_cropType", "type": "string" }, { "internalType": "uint256", "name": "_quantity", "type": "uint256" }, { "internalType": "string", "name": "_harvestDate", "type": "string" }, { "internalType": "string", "name": "_farmLocation", "type": "string" }, { "internalType": "bytes32", "name": "_photoHash", "type": "bytes32" }, { "internalType": "string", "name": "_farmerName", "type": "string" }, { "internalType": "string", "name": "_farmerUsername", "type": "string" }], "name": "createBatchV2", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_batchId", "type": "string" }, { "internalType": "uint8", "name": "_newStatus", "type": "uint8" }], "name": "updateBatchStatus", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_batchId", "type": "string" }, { "internalType": "string", "name": "_inspectorId", "type": "string" }, { "internalType": "string", "name": "_result", "type": "string" }, { "internalType": "string", "name": "_notes", "type": "string" }], "name": "addInspection", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_farmerBatchId", "type": "string" }, { "internalType": "string", "name": "_farmerId", "type": "string" }, { "internalType": "string", "name": "_cropName", "type": "string" }, { "internalType": "uint256", "name": "_quantity", "type": "uint256" }, { "internalType": "string", "name": "_collectorId", "type": "string" }], "name": "addCollection", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_batchId", "type": "string" }, { "internalType": "string", "name": "_herbType", "type": "string" }, { "internalType": "uint256", "name": "_quantity", "type": "uint256" }, { "internalType": "string", "name": "_storageLocation", "type": "string" }], "name": "recordReception", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_batchId", "type": "string" }, { "internalType": "uint256", "name": "_quantityToDispatch", "type": "uint256" }, { "internalType": "string", "name": "_destination", "type": "string" }], "name": "recordDispatch", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_productId", "type": "string" }, { "internalType": "string", "name": "_sourceBatchId", "type": "string" }, { "internalType": "string", "name": "_productType", "type": "string" }, { "internalType": "uint256", "name": "_quantityProcessed", "type": "uint256" }, { "internalType": "uint256", "name": "_wastage", "type": "uint256" }, { "internalType": "uint256", "name": "_processingDate", "type": "uint256" }, { "internalType": "uint256", "name": "_expiryDate", "type": "uint256" }, { "internalType": "string", "name": "_manufacturerId", "type": "string" }], "name": "createProduct", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
        // Profile setters
        { "inputs": [{ "internalType": "string", "name": "_name", "type": "string" }, { "internalType": "string", "name": "_username", "type": "string" }], "name": "setFarmerProfile", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_name", "type": "string" }, { "internalType": "string", "name": "_username", "type": "string" }], "name": "setAuditorProfile", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_name", "type": "string" }, { "internalType": "string", "name": "_username", "type": "string" }], "name": "setCollectorProfile", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_name", "type": "string" }, { "internalType": "string", "name": "_username", "type": "string" }], "name": "setManufacturerProfile", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
        { "inputs": [{ "internalType": "string", "name": "_name", "type": "string" }, { "internalType": "string", "name": "_username", "type": "string" }], "name": "setDistributorProfile", "outputs": [], "stateMutability": "nonpayable", "type": "function" }
    ],

    // Media storage (Pinata IPFS)
    PINATA_GATEWAY: 'https://pink-decisive-woodpecker-623.mypinata.cloud/ipfs/',
    PINATA_UPLOAD_URL: 'https://api.pinata.cloud/pinning/pinFileToIPFS',
    PINATA_JWT: 'd9f10a4440f6f552a5bd', // Your Pinata JWT token
    IMAGE_BASE_URL: 'https://pink-decisive-woodpecker-623.mypinata.cloud/ipfs/', // Gateway for images

    // Ganache private key for signing transactions
    DEV_PRIVATE_KEY: '0x40e57a95f510a8c1a5a64f2c77f082394d0602af0460fc21c4007ece30fd5ad1',
    GANACHE_ACCOUNT: '0xF014B06fFFa5cF813358Cb3528014cf992dE47C2'
};

// Back-compat alias so pages using AppConfig continue to work
window.AppConfig = window.config;
